test

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -28,8 +28,7 @@ jobs:
           BACKEND_URL: ${{ secrets.BACKEND_URL }}
         run: |
           cd frontend  # Change to the frontend directory
-          run: npm run build # Use `generate` if you're using Nuxt.js or another static site generator
-
+          npm run build || { echo "Build failed"; exit 1; }
       - name: Install SSH client
         run: sudo apt-get install -y sshpass
 
